spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/financas}
spring.datasource.username=${DB_USERNAME:financas}
spring.datasource.password=${DB_PASSWORD:financas}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
