spring.application.name=financas
spring.profiles.active=dev

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

app.jwt.secret=${JWT_SECRET:troque-essa-chave-em-producao-com-pelo-menos-32-bytes-aleatorios}
app.jwt.expiration-hours=${JWT_EXPIRATION_HOURS:24}
