spring.application.name=financas
spring.profiles.active=dev

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
